# https://dart.dev/tools/pub/pubspec

name: frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Latest version available on pub.dev.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 
  # firebase_core:
  # firebase_auth:

  cupertino_icons: ^1.0.8 # iOS style icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: JFOpenHuninn
      fonts:
        - asset: assets/fonts/jf-openhuninn-2.0.ttf
