# Generated by Django 5.1.3 on 2024-11-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakka_text', models.CharField(max_length=50)),
                ('meaning', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='word_images/')),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('pinyin', models.CharField(max_length=50)),
            ],
        ),
    ]
